### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by koji** [koji/nes-components#120]

**Comment by koji** [comment]
## ToDo
- [ ] rollup --> webpack
- [ ] introduce https://github.com/formium/tsdx
- [ ] Support styled-components
- [ ] Update for the latest nes.css
